# lumra_config/views/__init__.py
# Auto-rebuilt oleh lumra_fix.py

from .api_views import (
    submit_requisition,
    submit_purchases,
    approve_requisition,
    confirm_receipt,
    submit_stock_allocation,
    get_location_stock,
)

from .auth_views import (
    login_view,
    logout_view,
    profile_view,
    settings_view,
)

from .customer_views import (
    customer_list,
    customer_detail,
    customer_create,
    customer_update,
    customer_delete,
    customer_redeem_points,
)

from .dashboard_views import (
    dashboard_view,
    notification_view,
    api_dashboard_data,
    api_dashboard_chart_data,
)

from .helpers import (
    parse_date_aware,
    safe_get,
    safe_related,
    model_has_field,
    safe_select_related,
    smart_currency_format,
    safe_percent_format,
    get_empty_message,
    check_queryset_empty,
    create_empty_context,
    create_error_context,
)

from .inventory_views import (
    products_import_template,
    products_import,
    products_view,
    product_detail_view,
    stock_planning_view,
    locations_view,
)

from .masterdata_views import (
    categories_list,
    category_create,
    category_update,
    category_delete,
    units_list,
    unit_create,
    unit_update,
    unit_delete,
    vendors_list,
    vendor_create,
    vendor_update,
    vendor_delete,
)

from .misc_views import (
    get_user_permissions,
    pos_view,
    pos_create_order,
    purchasing_view,
    sales_history_view,
    sales_history_products_view,
    sales_performance_view,
    customers_view,
    add_customer_view,
    view_customer_view,
    edit_customer_view,
    delete_customer_view,
    campaign_list_view,
    add_campaign_view,
    edit_campaign_view,
    delete_campaign_view,
    discount_list_view,
    add_discount_view,
    edit_discount_view,
    delete_discount_view,
    loyalty_members_view,
    add_loyalty_member_view,
    edit_loyalty_member_view,
    delete_loyalty_member_view,
    financial_reports_view,
    market_insights_view,
    trends_analysis_view,
    activity_log_view,
    users_view,
    profile_view,
    settings_view,
    system_status_view,
    business_settings_view,
    business_feature_matrix_view,
    business_form_general_view,
    user_roles_permissions_view,
    download_report_view,
    export_trends_view,
    about_view,
    contact_view,
    search_view,
)

from .pricing_views import (
    supplier_price_list,
    supplier_price_form,
    supplier_price_delete,
)

from .production_views import (
    recipe_list,
    recipe_form,
    recipe_detail,
    recipe_delete,
)

from .report_views import (
    sales_report,
    transaction_summary,
    transfer_report,
    requisition_report,
    purchasing_report,
    report_inventory_log,
    report_inventory_low,
    report_inventory_stock,
    report_profit_loss_detail,
    report_sales_by_outlet,
    report_sales_by_payment,
    report_sales_by_product,
    report_sales_summary,
)

from .stock_movement_views import (
    stock_movement_view,
    export_stock_movement,
    add_stock_movement_view,
)

from .stock_opname_views import (
    is_manager,
    stock_opname_locations,
    stock_opname_form,
    stock_opname_approvals,
    stock_opname_approval_detail,
)

__all__ = [
    'about_view',
    'activity_log_view',
    'add_campaign_view',
    'add_customer_view',
    'add_discount_view',
    'add_loyalty_member_view',
    'add_stock_movement_view',
    'api_dashboard_chart_data',
    'api_dashboard_data',
    'approve_requisition',
    'business_feature_matrix_view',
    'business_form_general_view',
    'business_settings_view',
    'campaign_list_view',
    'categories_list',
    'category_create',
    'category_delete',
    'category_update',
    'check_queryset_empty',
    'confirm_receipt',
    'contact_view',
    'create_empty_context',
    'create_error_context',
    'customer_create',
    'customer_delete',
    'customer_detail',
    'customer_list',
    'customer_redeem_points',
    'customer_update',
    'customers_view',
    'dashboard_view',
    'delete_campaign_view',
    'delete_customer_view',
    'delete_discount_view',
    'delete_loyalty_member_view',
    'discount_list_view',
    'download_report_view',
    'edit_campaign_view',
    'edit_customer_view',
    'edit_discount_view',
    'edit_loyalty_member_view',
    'export_stock_movement',
    'export_trends_view',
    'financial_reports_view',
    'get_empty_message',
    'get_location_stock',
    'get_user_permissions',
    'is_manager',
    'locations_view',
    'login_view',
    'logout_view',
    'loyalty_members_view',
    'market_insights_view',
    'model_has_field',
    'notification_view',
    'parse_date_aware',
    'pos_create_order',
    'pos_view',
    'product_detail_view',
    'products_import',
    'products_import_template',
    'products_view',
    'profile_view',
    'purchasing_report',
    'purchasing_view',
    'recipe_delete',
    'recipe_detail',
    'recipe_form',
    'recipe_list',
    'report_inventory_log',
    'report_inventory_low',
    'report_inventory_stock',
    'report_profit_loss_detail',
    'report_sales_by_outlet',
    'report_sales_by_payment',
    'report_sales_by_product',
    'report_sales_summary',
    'requisition_report',
    'safe_get',
    'safe_percent_format',
    'safe_related',
    'safe_select_related',
    'sales_history_products_view',
    'sales_history_view',
    'sales_performance_view',
    'sales_report',
    'search_view',
    'settings_view',
    'smart_currency_format',
    'stock_movement_view',
    'stock_opname_approval_detail',
    'stock_opname_approvals',
    'stock_opname_form',
    'stock_opname_locations',
    'stock_planning_view',
    'submit_purchases',
    'submit_requisition',
    'submit_stock_allocation',
    'supplier_price_delete',
    'supplier_price_form',
    'supplier_price_list',
    'system_status_view',
    'transaction_summary',
    'transfer_report',
    'trends_analysis_view',
    'unit_create',
    'unit_delete',
    'unit_update',
    'units_list',
    'user_roles_permissions_view',
    'users_view',
    'vendor_create',
    'vendor_delete',
    'vendor_update',
    'vendors_list',
    'view_customer_view',
]
