# Generated by Codex on 2026-04-15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lumra_config', '0002_salestarget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarehouseZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=120)),
                ('zone_type', models.CharField(choices=[('rack', 'Rack'), ('bulk', 'Bulk'), ('staging', 'Staging'), ('cold', 'Cold Storage'), ('frozen', 'Frozen'), ('other', 'Other')], default='rack', max_length=20)),
                ('capacity', models.PositiveIntegerField(default=0, help_text='Capacity in unit/pcs (simple).')),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='lumra_config.location')),
            ],
            options={
                'db_table': 'lumra_config_warehouse_zones',
                'ordering': ['location__name', 'code'],
                'unique_together': {('location', 'code')},
            },
        ),
        migrations.CreateModel(
            name='InventoryBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('quantity_on_hand', models.PositiveIntegerField(default=0)),
                ('production_date', models.DateField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, db_index=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_batches', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='lumra_config.location')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='lumra_config.productvariant')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='batches', to='lumra_config.warehousezone')),
            ],
            options={
                'db_table': 'lumra_config_inventory_batches',
                'ordering': ['-created_at'],
                'unique_together': {('location', 'code')},
            },
        ),
        migrations.CreateModel(
            name='StockAdjustmentReason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lumra_config_stock_adjustment_reasons',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('name', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_boms', to=settings.AUTH_USER_MODEL)),
                ('finished_variant', models.ForeignKey(help_text='The produced/finished SKU.', on_delete=django.db.models.deletion.PROTECT, related_name='boms', to='lumra_config.productvariant')),
            ],
            options={
                'db_table': 'production_boms',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lumra_config.billofmaterial')),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bom_components', to='lumra_config.productvariant')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lumra_config.unit')),
            ],
            options={
                'db_table': 'production_bom_items',
                'ordering': ['component__sku'],
                'unique_together': {('bom', 'component')},
            },
        ),
        migrations.CreateModel(
            name='ProductionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('on_hold', 'On Hold'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('target_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('produced_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('scheduled_date', models.DateField(blank=True, db_index=True, null=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('priority', models.CharField(default='Normal', max_length=20)),
                ('line', models.CharField(blank=True, max_length=80)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='production_orders', to='lumra_config.billofmaterial')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_production_orders', to=settings.AUTH_USER_MODEL)),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lumra_config.unit')),
            ],
            options={
                'db_table': 'production_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionMaterialConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('consumed_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consumptions', to='lumra_config.productvariant')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='lumra_config.productionorder')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lumra_config.unit')),
            ],
            options={
                'db_table': 'production_material_consumptions',
                'ordering': ['-consumed_at'],
            },
        ),
        migrations.CreateModel(
            name='FinishedGoodsReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_received', models.DecimalField(decimal_places=2, max_digits=12)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('finished_variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_receipts', to='lumra_config.productvariant')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='finished_receipts', to='lumra_config.location')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='lumra_config.productionorder')),
            ],
            options={
                'db_table': 'production_finished_goods_receipts',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductionWasteRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_type', models.CharField(choices=[('scrap', 'Scrap'), ('spoilage', 'Spoilage'), ('rework', 'Rework'), ('other', 'Other')], default='scrap', max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recorded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='waste_records', to='lumra_config.productvariant')),
                ('production_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wastes', to='lumra_config.productionorder')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lumra_config.unit')),
            ],
            options={
                'db_table': 'production_waste_records',
                'ordering': ['-recorded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='billofmaterial',
            index=models.Index(fields=['finished_variant', 'is_active'], name='production_b_finished_3f2b9d_idx'),
        ),
    ]

