# Generated by Django 6.0.3 on 2026-04-16 02:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumra_config', '0005_system_security_settings_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('payment_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('payment_method', models.CharField(choices=[('cash', 'Tunai'), ('debit_card', 'Kartu Debit'), ('credit_card', 'Kartu Kredit'), ('qris', 'QRIS'), ('bank_transfer', 'Transfer Bank'), ('check', 'Cek'), ('other', 'Lainnya')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('failed', 'Failed'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lumra_config_payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.CreateModel(
            name='ProductBatches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(db_index=True, help_text='Nomor batch/lot dari supplier atau produksi', max_length=100)),
                ('manufacturing_date', models.DateField(help_text='Tanggal produksi/manufacturing')),
                ('expiry_date', models.DateField(db_index=True, help_text='Tanggal kadaluarsa produk')),
                ('quantity_in', models.DecimalField(decimal_places=2, help_text='Qty batch yang masuk', max_digits=12)),
                ('quantity_available', models.DecimalField(decimal_places=2, default=0, help_text='Qty yang masih tersedia', max_digits=12)),
                ('supplier_batch_number', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lumra_config_productbatches',
                'ordering': ['expiry_date'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(choices=[('defective', 'Produk Cacat'), ('wrong_item', 'Item Salah'), ('quality_issue', 'Masalah Kualitas'), ('customer_request', 'Permohonan Pelanggan'), ('expired', 'Produk Kadaluarsa'), ('other', 'Lainnya')], default='customer_request', max_length=20)),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'lumra_config_returnitems',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('retur_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('retur_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], db_index=True, default='pending', max_length=20)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lumra_config_returns',
                'ordering': ['-retur_date'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('purchase_in', 'Pembelian Masuk'), ('sales_out', 'Penjualan Keluar'), ('production_in', 'Produksi Selesai'), ('production_out', 'Konsumsi Produksi'), ('retur_in', 'Retur Masuk'), ('transfer_in', 'Transfer Masuk'), ('transfer_out', 'Transfer Keluar'), ('adjustment_in', 'Penyesuaian Masuk'), ('adjustment_out', 'Penyesuaian Keluar')], db_index=True, max_length=20)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reference_type', models.CharField(blank=True, help_text="Tipe dokumen: 'order', 'requisition', 'production', 'retur', etc", max_length=50)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='ID dari dokumen referensi', null=True)),
                ('reference_number', models.CharField(blank=True, help_text='Nomor dokumen: INV-001, PO-001, etc', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'lumra_config_stockmovement',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payments',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='lumra_config.order'),
        ),
        migrations.AddField(
            model_name='payments',
            name='received_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='productbatches',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_batches', to='lumra_config.location'),
        ),
        migrations.AddField(
            model_name='productbatches',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='expiry_batches', to='lumra_config.productvariant'),
        ),
        migrations.AddField(
            model_name='productbatches',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_batches', to='lumra_config.vendor'),
        ),
        migrations.AddField(
            model_name='returnitems',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lumra_config.productvariant'),
        ),
        migrations.AddField(
            model_name='returns',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_approved', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returns',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='returns_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='returns',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='lumra_config.customer'),
        ),
        migrations.AddField(
            model_name='returns',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='lumra_config.order'),
        ),
        migrations.AddField(
            model_name='returnitems',
            name='retur_header',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lumra_config.returns'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='lumra_config.location'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='lumra_config.productvariant'),
        ),
        migrations.AddIndex(
            model_name='payments',
            index=models.Index(fields=['order', 'payment_date'], name='lumra_confi_order_i_822eba_idx'),
        ),
        migrations.AddIndex(
            model_name='payments',
            index=models.Index(fields=['status', 'payment_date'], name='lumra_confi_status_d41c38_idx'),
        ),
        migrations.AddIndex(
            model_name='productbatches',
            index=models.Index(fields=['product', 'location'], name='lumra_confi_product_d7b685_idx'),
        ),
        migrations.AddIndex(
            model_name='productbatches',
            index=models.Index(fields=['expiry_date', 'quantity_available'], name='lumra_confi_expiry__fe7acf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productbatches',
            unique_together={('product', 'batch_number', 'location')},
        ),
        migrations.AddIndex(
            model_name='returns',
            index=models.Index(fields=['status', 'retur_date'], name='lumra_confi_status_90c274_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', 'location', 'created_at'], name='lumra_confi_product_6fe0cb_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['movement_type', 'created_at'], name='lumra_confi_movemen_83a14c_idx'),
        ),
    ]
