# Generated by Django 6.0.3 on 2026-04-16 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lumra_config', '0006_payments_productbatches_returnitems_returns_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(choices=[('retail', 'Retail/Personal'), ('wholesale', 'Wholesale'), ('restaurant', 'Restaurant'), ('hotel', 'Hotel'), ('clinic', 'Clinic')], default='retail', help_text='Tipe customer', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='cashier_id',
            field=models.ForeignKey(blank=True, help_text='Kasir yang handle', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_as_cashier', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Uang kembalian', max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='dining_option',
            field=models.CharField(blank=True, choices=[('dine_in', 'Makan di Tempat'), ('takeaway', 'Bungkus'), ('delivery', 'Delivery')], help_text='Opsi makan', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('draft', 'Draft/Quotation'), ('sales_order', 'Sales Order'), ('invoiced', 'Invoice'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='sales_order', help_text='Tipe order', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Juml yang sudah dibayar', max_digits=15),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, help_text='Metode pembayaran', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid')], db_index=True, default='pending', help_text='Status pembayaran', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='shift_id',
            field=models.CharField(blank=True, help_text='ID shift kasir', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='table_number',
            field=models.CharField(blank=True, help_text='Nomor meja (untuk dining in)', max_length=20),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='batch_id',
            field=models.ForeignKey(blank=True, help_text='Batch/lot produk', null=True, on_delete=django.db.models.deletion.SET_NULL, to='lumra_config.productbatches'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='cost_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Harga cost/modal', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Diskon nominal', max_digits=12),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_percent',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Diskon persen', max_digits=5),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.TextField(blank=True, help_text='Catatan item'),
        ),
        migrations.AddField(
            model_name='product',
            name='barcode',
            field=models.CharField(blank=True, db_index=True, help_text='Barcode/SKU produk', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='product',
            name='has_expiry',
            field=models.BooleanField(default=False, help_text='Apakah produk bisa expired?'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Status aktif/nonaktif'),
        ),
        migrations.AddField(
            model_name='product',
            name='max_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stok maksimal untuk autoorder', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='min_stock',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Stok minimal sebelum alert', max_digits=12),
        ),
        migrations.AddField(
            model_name='product',
            name='sell_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Harga jual standar', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='track_batch',
            field=models.BooleanField(default=False, help_text='Apakah produk perlu tracking batch?'),
        ),
        migrations.AddField(
            model_name='stock',
            name='reserved_quantity',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Qty yang di-reserve/hold', max_digits=12),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='default_location_id',
            field=models.ForeignKey(blank=True, help_text='Lokasi default', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users_default_location', to='lumra_config.location'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Status aktif/nonaktif'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(blank=True, help_text='Role/jabatan pengguna', max_length=100),
        ),
    ]
