# Generated by Django 6.0.3 on 2026-04-16 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumra_config', '0007_rename_production_b_finished_3f2b9d_idx_production__finishe_688ba4_idx_and_more'),
    ]

    operations = [
        migrations.RunSQL(
            "ALTER TABLE IF EXISTS lumra_config_productbatches RENAME TO lumra_config_product_batches;",
            "ALTER TABLE IF EXISTS lumra_config_product_batches RENAME TO lumra_config_productbatches;",
            state_operations=[
                migrations.AlterModelTable(name='productbatches', table='lumra_config_product_batches'),
            ]
        ),
        migrations.RunSQL(
            "ALTER TABLE IF EXISTS production_boms RENAME TO production_bill_of_materials;",
            "ALTER TABLE IF EXISTS production_bill_of_materials RENAME TO production_boms;",
            state_operations=[
                migrations.AlterModelTable(name='billofmaterial', table='production_bill_of_materials'),
            ]
        ),
    ]
