# Generated by Django 5.1 on 2026-04-17 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumra_config', '0015_add_missing_production_tables'),
    ]

    operations = [
        # Index rename operations removed - indices don't exist in DB
        # These will need to be handled separately if needed
    ]
