# Generated by Django 6.0.3 on 2026-04-27 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lumra_config', '0016_fix_indices_cleanup'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],
            state_operations=[
                migrations.RenameIndex(
                    model_name='billofmaterial',
                    new_name='production__finishe_9b629f_idx',
                    old_name='production_b_finished_3f2b9d_idx',
                ),
                migrations.RenameIndex(
                    model_name='productbatches',
                    new_name='lumra_confi_product_4ab76a_idx',
                    old_name='lumra_confi_product_d7b685_idx',
                ),
                migrations.RenameIndex(
                    model_name='productbatches',
                    new_name='lumra_confi_expiry__d423ee_idx',
                    old_name='lumra_confi_expiry__fe7acf_idx',
                ),
            ],
        ),
    ]
