# lumra_config/inventory/views.py
# Auto-generated oleh lumra_fix.py
# Stub ini mengimpor ulang semua fungsi dari lumra_config.views
# sehingga urls.py bisa menggunakan path 'lumra_config.inventory.views.fungsi_name'

from lumra_config.views import (
    products_view as products,
    products_import_template,
    products_import,
    stock_planning_view,
    stock_movement_view,
    add_stock_movement_view,
    export_stock_movement,
    batch_list,
    batch_form,
    batch_detail,
    expiry_tracking,
    requisition_list,
    requisition_form,
    requisition_detail,
    supplier_price_list,
    supplier_price_form,
    supplier_price_delete,
    approve_requisition,
    submit_stock_allocation,
    warehouse_zones,
    warehouse_zone_form,
    adjustment_reasons,
    supplier_evaluation,
    # Print views
    print_invoice,
    print_sales_order,
    print_quotation,
    print_purchase_order,
    print_delivery_note,
    print_packing_slip,
    print_payment_receipt,
    print_receipt,
    print_production_order,
    print_credit_note,
    print_stock_opname,
)

__all__ = [
    'products',
    'products_import_template',
    'products_import',
    'stock_planning_view',
    'stock_movement_view',
    'add_stock_movement_view',
    'export_stock_movement',
    'batch_list',
    'batch_form',
    'batch_detail',
    'expiry_tracking',
    'requisition_list',
    'requisition_form',
    'requisition_detail',
    'supplier_price_list',
    'supplier_price_form',
    'supplier_price_delete',
    'approve_requisition',
    'submit_stock_allocation',
    'warehouse_zones',
    'warehouse_zone_form',
    'adjustment_reasons',
    'supplier_evaluation',
    'print_invoice',
    'print_sales_order',
    'print_quotation',
    'print_purchase_order',
    'print_delivery_note',
    'print_packing_slip',
    'print_payment_receipt',
    'print_receipt',
    'print_production_order',
    'print_credit_note',
    'print_stock_opname',
]
